### ISSUE TITLE
Research contract requirements based on game specifications

### ISSUE THREAD

**Issue by jamesdaus** [dev-launchers/blockchain__general#5]
- Research token and NFT contracts, and how they can interact
- Using MVP description, find what contracts need to be written to achieve minimum functionality

**Comment by Zorro909** [comment]
ERC777 was incompatible with Uniswap V1, however V2 added compatibility and therefore all forks of Uniswap V2 (i.e. Sushiswap/Quickswap etc.) also support it. 
The Core problem about reentrancy attacks will need to be factored in to our design though. (All state changes need to be done before any $DEVS tokens are transferred)
